import { AvatarColor } from './avatar-colors';
import { ChatItemType, MessageType } from './chat';

export const user = {
  firstName: 'Parsa',
  lastName: 'Chavoshi',
  email: 'parypary82@gmail.com',
  avatarImage: '',
  avatarColor: 'yellow' as AvatarColor,
  isOnline: true,
  lastSeen: '2025-01-10 08:45:32.672',
};

export const messageItems: MessageType[] = [
  {
    messageId: 'msg_1',
    type: 'sent',
    messageText: 'See you soon!',
    time: '2025-01-10 09:26:28.332',
    status: 'seen',
  },
  {
    messageId: 'msg_2',
    type: 'received',
    messageText: 'Happy New Year!',
    time: '2025-01-10 09:30:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_3',
    type: 'received',
    messageText: 'روباه سریع از روی سگ تنبل می‌پرد.',
    time: '2025-01-10 09:10:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_4',
    type: 'received',
    messageText: 'من در راه هستم.',
    time: '2025-01-10 08:15:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_5',
    type: 'sent',
    messageText: "Let's meet at 5 PM.",
    time: '2025-01-10 09:35:28.332',
    status: 'sent',
  },
  {
    messageId: 'msg_6',
    type: 'sent',
    messageText: 'The quick brown fox jumps over the lazy dog.',
    time: '2025-01-10 09:35:28.332',
    status: 'seen',
  },
  {
    messageId: 'msg_7',
    type: 'received',
    messageText: 'سال نو مبارک!',
    time: '2025-01-10 10:29:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_8',
    type: 'sent',
    messageText: 'صبح بخیر! امیدوارم روز خوبی داشته باشید.',
    time: '2025-01-10 07:36:28.332',
    status: 'seen',
  },
  {
    messageId: 'msg_9',
    type: 'received',
    messageText: 'Happy New Year!',
    time: '2025-01-10 16:56:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_10',
    type: 'received',
    messageText: 'Good morning! Hope you have a great day ahead.',
    time: '2025-01-10 01:14:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_11',
    type: 'sent',
    messageText:
      'این یک پیام طولانی است که جزئیات پروژه جدید ما را توضیح می‌دهد. ما باید گزارش را نهایی کنیم و قبل از موعد تحویل دهیم.',
    time: '2025-01-10 12:53:28.332',
    status: 'seen',
  },
  {
    messageId: 'msg_12',
    type: 'received',
    messageText: 'سلام! حال شما چطور است؟',
    time: '2025-01-10 02:36:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_13',
    type: 'received',
    messageText: 'من بیرون منتظرم.',
    time: '2025-01-10 10:52:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_14',
    type: 'received',
    messageText: 'The quick brown fox jumps over the lazy dog.',
    time: '2025-01-10 06:45:28.332',
    status: 'none',
  },
  {
    messageId: 'msg_15',
    type: 'sent',
    messageText:
      'این یک پیام طولانی است که جزئیات پروژه جدید ما را توضیح می‌دهد. ما باید گزارش را نهایی کنیم و قبل از موعد تحویل دهیم.',
    time: '2025-01-10 07:45:28.332',
    status: 'seen',
  },
  {
    messageId: 'msg_16',
    type: 'sent',
    messageText:
      'This is a long message explaining the details of our new project. We need to finalize the report and submit it before the deadline.',
    time: '2025-01-10 10:49:28.332',
    status: 'seen',
  },
  {
    messageId: 'msg_17',
    type: 'sent',
    messageText: "Let's meet at 5 PM.",
    time: '2025-01-10 03:37:28.332',
    status: 'error',
  },
  {
    messageId: 'msg_18',
    type: 'sent',
    messageText:
      'این یک پیام طولانی است که جزئیات پروژه جدید ما را توضیح می‌دهد. ما باید گزارش را نهایی کنیم و قبل از موعد تحویل دهیم.',
    time: '2025-01-10 07:32:28.332',
    status: 'sent',
  },
  {
    messageId: 'msg_19',
    type: 'sent',
    messageText: "Let's meet at 5 PM.",
    time: '2025-01-10 09:35:28.332',
    status: 'sending',
  },
  {
    messageId: 'msg_20',
    type: 'received',
    messageText: 'Happy New Year!',
    time: '2025-01-10 10:37:28.332',
    status: 'none',
  },
];

export const chatItems: ChatItemType[] = [
  {
    connectId: '1',
    avatarColor: 'blue',
    avatarImageSrc: '',
    firstName: 'محمد',
    lastName: 'رضایی',
    lastMessage: 'سلام، امروز چطوری؟ امیدوارم که روز خوبی داشته باشی.',
    newMessageCount: 2,
    isOnline: true,
    time: '2025-01-09 10:15:17.728',
    status: 'seen',
  },
  {
    connectId: '2',
    avatarColor: 'green',
    avatarImageSrc: '',
    firstName: 'Alice',
    lastName: 'Johnson',
    lastMessage: 'I have reviewed the document, and I think we need to make some changes.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-08 18:10:10.540',
    status: 'sent',
  },
  {
    connectId: '3',
    avatarColor: 'orange',
    avatarImageSrc: '',
    firstName: 'سارا',
    lastName: 'کاظمی',
    lastMessage: 'ممنون از پیام شما. حتماً در اولین فرصت پاسخ خواهم داد.',
    newMessageCount: 1,
    isOnline: true,
    time: '2024-09-03 22:30:45.123',
    status: 'seen',
  },
  {
    connectId: '4',
    avatarColor: 'purple',
    avatarImageSrc: '',
    firstName: 'David',
    lastName: 'Miller',
    lastMessage: 'Let’s meet tomorrow morning at the usual spot.',
    newMessageCount: 0,
    isOnline: false,
    time: '2024-06-04 08:45:32.672',
    status: 'sent',
  },
  {
    connectId: '5',
    avatarColor: 'red',
    avatarImageSrc: '',
    firstName: 'زهرا',
    lastName: 'نعمتی',
    lastMessage: 'باشه، بعد از ظهر در موردش صحبت می‌کنیم.',
    newMessageCount: 3,
    isOnline: true,
    time: '2025-01-05 12:00:00.000',
    status: 'seen',
  },
  {
    connectId: '6',
    avatarColor: 'yellow',
    avatarImageSrc: '',
    firstName: 'Frank',
    lastName: 'Wilson',
    lastMessage: 'I will send you the details once I have them.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-06 14:20:15.225',
    status: 'none',
  },
  {
    connectId: '7',
    avatarColor: 'blue',
    avatarImageSrc: '',
    firstName: 'نوید',
    lastName: 'فرهادی',
    lastMessage: 'لطفا لیست خرید رو قبل از ساعت ۶ برام ارسال کن.',
    newMessageCount: 1,
    isOnline: true,
    time: '2025-01-07 16:05:47.897',
    status: 'sending',
  },
  {
    connectId: '8',
    avatarColor: 'green',
    avatarImageSrc: '',
    firstName: 'Henry',
    lastName: 'Martinez',
    lastMessage: 'Thanks for your help! I really appreciate it.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-08 09:35:28.332',
    status: 'sent',
  },
  {
    connectId: '9',
    avatarColor: 'orange',
    avatarImageSrc: '',
    firstName: 'بهار',
    lastName: 'موسوی',
    lastMessage: 'امشب برای شام برنامه‌ای داری یا می‌خواهی بیرون بریم؟',
    newMessageCount: 2,
    isOnline: true,
    time: '2025-01-09 01:50:11.103',
    status: 'seen',
  },
  {
    connectId: '10',
    avatarColor: 'purple',
    avatarImageSrc: '',
    firstName: 'Jack',
    lastName: 'White',
    lastMessage: 'Alright, let’s discuss it tomorrow in our meeting.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-08 21:17:55.642',
    status: 'none',
  },
  {
    connectId: '11',
    avatarColor: 'blue',
    avatarImageSrc: '',
    firstName: 'Sophia',
    lastName: 'Brown',
    lastMessage: 'لطفاً برای جلسه هفته آینده برنامه‌ریزی کنید و به من اطلاع دهید.',
    newMessageCount: 1,
    isOnline: true,
    time: '2024-12-11 10:30:25.123',
    status: 'seen',
  },
  {
    connectId: '12',
    avatarColor: 'green',
    avatarImageSrc: '',
    firstName: 'علی',
    lastName: 'کریمی',
    lastMessage: 'I will call you back in a few minutes. Just finishing something up.',
    newMessageCount: 10,
    isOnline: false,
    time: '2025-01-02 16:30:30.789',
    status: 'error',
  },
];
