import { AvatarColor } from './avatar-colors';
import { ChatItemType } from './chat';

export const user = {
  firstName: 'Parsa',
  lastName: 'Chavoshi',
  email: 'parypary82@gmail.com',
  avatarImage: '',
  avatarColor: 'yellow' as AvatarColor,
};

export const chatItems: ChatItemType[] = [
  {
    connectId: '1',
    avatarColor: 'blue',
    avatarImageSrc: '',
    firstName: 'Alice',
    lastName: 'Johnson',
    lastMessage: 'Hey, how are you?',
    newMessageCount: 2,
    isOnline: true,
    time: '2025-01-01 20:15:17.728',
    status: 'seen',
  },
  {
    connectId: '2',
    avatarColor: 'green',
    avatarImageSrc: '',
    firstName: 'Bob',
    lastName: 'Smith',
    lastMessage: 'See you soon!',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-02 18:10:10.540',
    status: 'sent',
  },
  {
    connectId: '3',
    avatarColor: 'orange',
    avatarImageSrc: '',
    firstName: 'Charlie',
    lastName: 'Brown',
    lastMessage: 'What’s up?',
    newMessageCount: 1,
    isOnline: true,
    time: '2025-01-03 22:30:45.123',
    status: 'seen',
  },
  {
    connectId: '4',
    avatarColor: 'purple',
    avatarImageSrc: '',
    firstName: 'David',
    lastName: 'Miller',
    lastMessage: 'Let’s meet tomorrow.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-04 08:45:32.672',
    status: 'sent',
  },
  {
    connectId: '5',
    avatarColor: 'red',
    avatarImageSrc: '',
    firstName: 'Ella',
    lastName: 'Davis',
    lastMessage: 'Okay, noted!',
    newMessageCount: 3,
    isOnline: true,
    time: '2025-01-05 12:00:00.000',
    status: 'seen',
  },
  {
    connectId: '6',
    avatarColor: 'yellow',
    avatarImageSrc: '',
    firstName: 'Frank',
    lastName: 'Wilson',
    lastMessage: 'See you later.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-06 14:20:15.225',
    status: 'none',
  },
  {
    connectId: '7',
    avatarColor: 'blue',
    avatarImageSrc: '',
    firstName: 'Grace',
    lastName: 'Anderson',
    lastMessage: 'Can you send me that file?',
    newMessageCount: 1,
    isOnline: true,
    time: '2025-01-07 16:05:47.897',
    status: 'sending',
  },
  {
    connectId: '8',
    avatarColor: 'green',
    avatarImageSrc: '',
    firstName: 'Henry',
    lastName: 'Martinez',
    lastMessage: 'Thanks a lot!',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-08 09:35:28.332',
    status: 'sent',
  },
  {
    connectId: '9',
    avatarColor: 'orange',
    avatarImageSrc: '',
    firstName: 'Ivy',
    lastName: 'Taylor',
    lastMessage: 'Call me when you’re free.',
    newMessageCount: 2,
    isOnline: true,
    time: '2025-01-09 19:50:11.103',
    status: 'seen',
  },
  {
    connectId: '10',
    avatarColor: 'purple',
    avatarImageSrc: '',
    firstName: 'Jack',
    lastName: 'White',
    lastMessage: 'Alright, talk soon.',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-10 21:17:55.642',
    status: 'none',
  },
  {
    connectId: '11',
    avatarColor: 'red',
    avatarImageSrc: '',
    firstName: 'Karen',
    lastName: 'Harris',
    lastMessage: 'Good night!',
    newMessageCount: 1,
    isOnline: true,
    time: '2025-01-11 23:45:30.789',
    status: 'sent',
  },
  {
    connectId: '12',
    avatarColor: 'yellow',
    avatarImageSrc: '',
    firstName: 'Leo',
    lastName: 'Clark',
    lastMessage: 'Got it!',
    newMessageCount: 0,
    isOnline: false,
    time: '2025-01-12 07:20:14.002',
    status: 'none',
  },
];
